# Generated by Django 4.2.21 on 2025-05-26 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('EMI_REMINDER', 'EMI Reminder'), ('PAYMENT_CONFIRMATION', 'Payment Confirmation'), ('OVERDUE_ALERT', 'Overdue Alert'), ('CREDIT_UTILIZATION', 'Credit Utilization Alert'), ('LOAN_COMPLETION', 'Loan Completion'), ('WELCOME', 'Welcome Message')], max_length=30, unique=True)),
                ('email_subject', models.CharField(blank=True, max_length=200)),
                ('email_body', models.TextField(blank=True)),
                ('push_title', models.CharField(blank=True, max_length=200)),
                ('push_body', models.TextField(blank=True)),
                ('sms_body', models.TextField(blank=True)),
                ('variables_help', models.TextField(blank=True, help_text='Available variables: {user_name}, {emi_amount}, {due_date}, {card_name}, {loan_name}, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emi_email_enabled', models.BooleanField(default=True)),
                ('emi_push_enabled', models.BooleanField(default=True)),
                ('emi_sms_enabled', models.BooleanField(default=False)),
                ('emi_reminder_days_before', models.IntegerField(default=3)),
                ('payment_confirmation_email', models.BooleanField(default=True)),
                ('payment_confirmation_push', models.BooleanField(default=True)),
                ('overdue_email_enabled', models.BooleanField(default=True)),
                ('overdue_push_enabled', models.BooleanField(default=True)),
                ('overdue_sms_enabled', models.BooleanField(default=True)),
                ('credit_utilization_alert_enabled', models.BooleanField(default=True)),
                ('credit_utilization_threshold', models.IntegerField(default=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('EMI_REMINDER', 'EMI Reminder'), ('PAYMENT_CONFIRMATION', 'Payment Confirmation'), ('OVERDUE_ALERT', 'Overdue Alert'), ('CREDIT_UTILIZATION', 'Credit Utilization Alert'), ('LOAN_COMPLETION', 'Loan Completion'), ('GENERAL', 'General Notification')], max_length=30)),
                ('delivery_method', models.CharField(choices=[('EMAIL', 'Email'), ('PUSH', 'Push Notification'), ('SMS', 'SMS'), ('IN_APP', 'In-App')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('READ', 'Read')], default='PENDING', max_length=20)),
                ('emi_id', models.IntegerField(blank=True, null=True)),
                ('credit_card_id', models.IntegerField(blank=True, null=True)),
                ('loan_id', models.IntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('fcm_message_id', models.CharField(blank=True, max_length=200, null=True)),
                ('email_message_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
