# Generated by Django 4.2.21 on 2025-05-31 05:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardemi',
            name='total_emi_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total EMI amount (emi_amount * total_duration)', max_digits=15),
        ),
    ]
