# Generated by Django 4.2.21 on 2025-05-31 05:58

from django.db import migrations
from decimal import Decimal


def populate_total_emi_amount(apps, schema_editor):
    """Populate total_emi_amount field for existing records"""
    CreditCardEMI = apps.get_model('credit_cards', 'CreditCardEMI')
    
    for emi in CreditCardEMI.objects.filter(total_emi_amount=Decimal('0.00')):
        emi.total_emi_amount = emi.emi_amount * emi.total_duration
        emi.save()


def reverse_populate_total_emi_amount(apps, schema_editor):
    """Reverse migration - reset total_emi_amount to 0"""
    CreditCardEMI = apps.get_model('credit_cards', 'CreditCardEMI')
    CreditCardEMI.objects.update(total_emi_amount=Decimal('0.00'))


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0002_creditcardemi_total_emi_amount'),
    ]

    operations = [
        migrations.RunPython(
            populate_total_emi_amount,
            reverse_populate_total_emi_amount
        ),
    ]
