# Generated by Django 4.2.21 on 2025-05-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0003_auto_20250531_0558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcardemi',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='creditcardemi',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of the EMI plan', null=True),
        ),
        migrations.AddField(
            model_name='creditcardemi',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date of the EMI plan', null=True),
        ),
        migrations.AlterField(
            model_name='creditcardemi',
            name='due_date',
            field=models.DateField(help_text='Legacy field - due date is now calculated from start_date'),
        ),
    ]
