# Generated by Django 4.2.21 on 2025-05-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0004_alter_creditcardemi_options_creditcardemi_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcardemi',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='creditcardemi',
            name='end_date',
            field=models.DateField(help_text='End date of the EMI plan'),
        ),
        migrations.AlterField(
            model_name='creditcardemi',
            name='start_date',
            field=models.DateField(help_text='Start date of the EMI plan'),
        ),
    ]
